// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwjxauwfoplmsenhfezm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3anhhdXdmb3BsbXNlbmhmZXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDI4NzIsImV4cCI6MjA2MzA3ODg3Mn0.2BGI7hiW929VIjflu9gFpz3Uv-oROTO6nFeATR4MZAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);